name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/xcodegen
          ~/Library/Caches/org.swift.swiftpm
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-build-${{ hashFiles('project.yml', 'Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Check cache status
      run: |
        echo "🔍 Cache status check..."
        echo "Cache key: ${{ runner.os }}-build-${{ hashFiles('project.yml', 'Package.swift') }}"
        
        if [ -d "~/Library/Developer/Xcode/DerivedData" ]; then
          echo "✅ DerivedData directory exists"
          ls -la ~/Library/Developer/Xcode/DerivedData/ | head -5
        else
          echo "📁 DerivedData directory not found yet"
        fi
        
        if [ -d "~/.cache/xcodegen" ]; then
          echo "✅ XcodeGen cache exists"
        else
          echo "📁 XcodeGen cache not found yet"
        fi
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.4"
    - name: XcodeGen
      uses: xavierLowmiller/xcodegen-action@1.2.4
      with:
        spec: project.yml
        version: 2.43.0
    - name: Run iOS tests
      run: |
        set -o pipefail && xcodebuild test \
          -scheme bitchatTests_iOS \
          -destination "platform=iOS Simulator,name=iPhone 16" | xcpretty
